In [20]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [21]:
df = pd.read_csv("movies_metadata.csv")
df.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [23]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [24]:
df.shape

(45466, 24)

In [25]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [26]:
 df =df.drop_duplicates().reset_index(drop=True)

In [27]:
df = df[["title","overview","genres","tagline","vote_average","popularity"]]

In [28]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [29]:
df = df.dropna(subset=["title"])

In [30]:
df["overview"] = df["overview"].fillna('')

In [31]:
df.iloc[0]["genres"]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [32]:
import ast

df['genres'] = df['genres'].apply(
    lambda x: " ".join([i["name"] for i in ast.literal_eval(x)])
)

In [33]:
df.head(1)

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943

In [34]:
df["tagline"] = df["tagline"].fillna('')

In [35]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [36]:
df['tags'] = df['overview']+" "+df["genres"]+" "+df["tagline"]

In [37]:
df.head(1)

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."

In [57]:
df["tags"][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [59]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [61]:
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [63]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

In [67]:
def preprocess_text(text):
    #lowercase
    text = str(text).lower()
    #remove the punctuation
    text = re.sub(r'[^a-zA-z\s]','',text)

    words = text.split()
    #remove stopwords
    words = [word for word in words if word not in stop_words]

    #lemmatize
    words=[lemmatizer.lemmatize(word) for word in words]
    return ' '.join(words)

In [69]:
df['tags']=df['tags'].apply(preprocess_text)

In [75]:
df["tags"][0]

'led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

In [77]:
df = df.reset_index(drop=True)

In [85]:
indices = pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [87]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [93]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [95]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [97]:
tfidf_matrix

<45447x50000 sparse matrix of type '<class 'numpy.float64'>'
	with 1548308 stored elements in Compressed Sparse Row format>

In [99]:
from sklearn.metrics.pairwise import cosine_similarity

In [115]:
def recommend(title,n = 10):
    if title not in indices:
        return ['Movie not found']

    idx =indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [133]:
recommend("Avatar")

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
43431                        Moontrap: Target Earth
6414     Lara Croft Tomb Raider: The Cradle of Life
9949                             A Trip to the Moon
14119                          The Three Musketeers
20372                                        Désiré
28403                        France société anonyme
43983                           Nightmare City 2035
Name: title, dtype: object

In [135]:
import pickle
pickle.dump(tfidf_matrix,open("tfidf_matrix.pkl",'wb'))
pickle.dump(indices,open("indices.pkl",'wb'))
df.to_pickle("df.pkl")
pickle.dump(tfidf,open("tfidf.pkl",'wb'))